steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - '${_GITHUB_REPO_URL}'
      - '/workspace/repo-src'

options:
  logging: NONE

substitutions:
  _GITHUB_REPO_URL: 'https://github.com/tran-haison/Demo-Todo-Backend.git'
  _DOCKERHUB_USERNAME: 'sonth2501'
  _IMAGE: 'todo-backend'
  _IMAGE_TAG: 'latest'
  _GKE_LOCATION: 'australia-southeast2'
  _GKE_CLUSTER: 'capstone-cluster'
