steps:
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=k8s/'
      - '--image=${_DOCKERHUB_USERNAME}/${_IMAGE}:${_IMAGE_TAG}'
      - '--location=${_GKE_LOCATION}'
      - '--cluster=${_GKE_CLUSTER}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DOCKERHUB_USERNAME: 'sonth2501'
  _IMAGE: 'todo-backend'
  _IMAGE_TAG: 'latest'
  _GKE_LOCATION: 'australia-southeast2'
  _GKE_CLUSTER: 'capstone-cluster'