apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        args: ["--bind_ip_all", "--auth"]
        ports:
        - containerPort: 27017
        envFrom:
        - secretRef:
            name: todo-backend-secrets
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-init-script
          mountPath: /docker-entrypoint-initdb.d/mongo-init.js
          subPath: mongo-init.js
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
      - name: mongodb-init-script
        configMap:
          name: mongodb-init-script
