apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:password123@mongodb:27017/todo-list?authSource=admin"
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "password123"
